main.tf, rds.tf, secrets.tf
Adicionando instância RDS do MySql
=> Add rds instance

rds.tf
Corrigindo configuração do rds para não gerar erro no apply
=> Update rds config

rds.tf
Atualizando senha e nome do banco de dados
=> Update database name and password

rds.tf, secrets.tf
Adicionando secret com os valores de acesso a base de dados
=> Add secrets

rds.tf, secrets.tf
Atualizando subnet group do banco de dados e atualizando secret
=> Update rds subnet group and update secrets

rds.tf, secrets.tf
Removendo security groups criados
=> Revert "Update rds subnet group and update secrets"

eks.tf
Voltando com alterações do eks souzamarcos/tech-challenge-terraform#13
=> Revert "Revert "Feature/add eks""

rds.tf
Atualizando versão do engine do RDS
=> chore: Update engine version

rds.tf, secrets.tf
Recriando RDS removido na PR souzamarcos/tech-challenge-terraform#23
=> Revert "Remove rds and update secret"

network.tf
Adicionando VPC, subnets, internet gateway e table route
=> feat: Add network

rds.tf
Atualizando subnet da base de dados rds
=> Update rds subnet

network.tf
Atualizando vpc e available zones
=> fix: Update vpc and azs

rds.tf
Atualizando a propriedade skip_final_snapshot do rds
=> fix: Update rds skip_final_snapshot

secrets.tf
=> feat: Update secret name

iam-role.tf, lambda.tf, log-group.tf
=> Lambda via terraform

lambda.tf
> Mudança propriedade do handler
>
=> Lambda via terraform - Mudando especificação do handler

api-gateway.tf, lambda.tf
=> Lambda via terraform - Adicionando api-gateway.tf

lambda.tf
=> Lambda via terraform - mudando nome do arquivo zip

api-gateway.tf
=> api-gateway.tf via terraform - tentando criar logs

lambda.tf
=> lambda.tf via terraform - adicionando permissão para ser invocado

secrets.tf
Recriando secret com outro nome
=> chore: Update secret name

dynamo.tf, iam-role.tf, lambda.tf
> Teste para adicionar dynamo com relação com  o lambda
> Arquivo terraform do dynamoDB + permissões para o lambda acessá-lo via iam + mudança no lambda para acrescentar variável de ambiente
=> dynamo.tf - Tentando comunicação dynamo.tf + lambda.tf

api-gateway.tf
=> api-gateway.tf - removendo config de logs all

iam-role.tf
=> iam-role.tf - + teste de políticas iam

iam-role.tf
=> iam-role.tf - mudando de servicerole para service-role

iam-role.tf
=> iam-role.tf - unindo todas as políticas num único lugar

dynamo.tf, iam-role.tf
=> dynamo.tf - removendo id do range_key

iam-role.tf, lambda.tf
=> Subindo lambda lendo secret

dynamo.tf
Diminuindo capacidade de leitura e escrita simultânea do dynamo db para não gerar custos
=> Reduce dynamodb read and write capacity

secrets.tf
=> secrets.tf - testando se o terraform modifica o valor de token já criado

lambda.tf, secrets.tf
=> secrets.tf - criando secret token_jwt

api-gateway.tf, eks.tf, iam-role.tf, lambda.tf
Adicionando nova policy para o node group do eks poder executar operações no dynamodb.
=> feature: Add new policy and add to eks node group

eks.tf
Reverts souzamarcos/tech-challenge-terraform#63
=> Revert "Remove eks"

eks.tf
Reverts souzamarcos/tech-challenge-terraform#65
=> Revert "Removendo eks.tf"

eks.tf
Reverts souzamarcos/tech-challenge-terraform#68
=> Revert "chore: Remove eks"

iam-role.tf, lambda.tf, rds.tf, secrets.tf
=> feat: Add databases, update secrets

lambda.tf, s3.tf
Criando bucket s3 e atualizando lambda
=> feat: Add s3 bucket and update lambda

eks.tf
Reverts souzamarcos/tech-challenge-terraform#78
=> Add eks.tf

sqs.tf
=> Add sqs queue

iam-role.tf
Atualizando policy para permitir o uso do sqs pelos pods do eks
=> chore: Update policy

eks.tf
=> chore: Update eks config

secrets.tf
=> chore: Update secret names

dynamo.tf
Atualizada o nome da PK do dynamo db
=> chore: Update dynamodb

dynamo.tf
Atualizando nome da tabela dynamo
=> fix: Update table name

dynamo.tf, iam-role.tf, lambda.tf
Mudando configurações de lambda de client para customer
=> Mudando configurações de lambda de client para customer

iam-role.tf
Mudança nas regras de permissão ao dynamo
=> Mudança nas regras de permissão ao dynamo

sqs.tf
=> chore: Remove sqs delay

secrets.tf
=> fix: Update secret name
